'use client';

import { useEffect, useRef, useState } from 'react';
import { useTheme } from 'next-themes';
import mermaid from 'mermaid';
import DOMPurify from 'dompurify';

interface MermaidProps {
  chart: string;
}

export function Mermaid({ chart }: MermaidProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string>('');
  const [error, setError] = useState<string | null>(null);
  const { resolvedTheme } = useTheme();

  useEffect(() => {
    const renderChart = async () => {
      if (!containerRef.current) return;

      // Reset error state
      setError(null);

      // Configure mermaid with theme
      mermaid.initialize({
        startOnLoad: false,
        theme: resolvedTheme === 'dark' ? 'dark' : 'default',
        securityLevel: 'strict',
        fontFamily: 'inherit',
      });

      try {
        const id = `mermaid-${Math.random().toString(36).slice(2, 9)}`;
        const { svg: renderedSvg } = await mermaid.render(id, chart);
        // Defense-in-depth: sanitize SVG even though Mermaid has securityLevel: 'strict'
        const sanitizedSvg = DOMPurify.sanitize(renderedSvg, {
          USE_PROFILES: { svg: true, svgFilters: true },
        });
        setSvg(sanitizedSvg);
      } catch (err) {
        console.error('Mermaid rendering error:', err);
        setError(err instanceof Error ? err.message : 'Unknown error');
        setSvg('');
      }
    };

    renderChart();
  }, [chart, resolvedTheme]);

  // Show error without dangerouslySetInnerHTML to prevent XSS
  if (error) {
    return (
      <div
        ref={containerRef}
        className="my-4 flex justify-center overflow-x-auto rounded-lg border bg-background p-4"
      >
        <pre className="text-destructive">Mermaid Error: {error}</pre>
      </div>
    );
  }

  // Note: dangerouslySetInnerHTML is safe here because:
  // 1. The SVG is generated by mermaid.render() from developer-authored MDX content
  // 2. Mermaid has built-in sanitization with securityLevel: 'strict'
  // 3. DOMPurify provides defense-in-depth sanitization as a second layer
  // 4. This is not user-generated content from external sources
  return (
    <div
      ref={containerRef}
      className="my-4 flex justify-center overflow-x-auto rounded-lg border bg-background p-4"
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
