'use client';

import { useEffect, useRef, useState } from 'react';
import { useTheme } from 'next-themes';
import mermaid from 'mermaid';

interface MermaidProps {
  chart: string;
}

export function Mermaid({ chart }: MermaidProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string>('');
  const { resolvedTheme } = useTheme();

  useEffect(() => {
    const renderChart = async () => {
      if (!containerRef.current) return;

      // Configure mermaid with theme
      mermaid.initialize({
        startOnLoad: false,
        theme: resolvedTheme === 'dark' ? 'dark' : 'default',
        securityLevel: 'strict',
        fontFamily: 'inherit',
      });

      try {
        const id = `mermaid-${Math.random().toString(36).slice(2, 9)}`;
        const { svg: renderedSvg } = await mermaid.render(id, chart);
        setSvg(renderedSvg);
      } catch (error) {
        console.error('Mermaid rendering error:', error);
        setSvg(`<pre class="text-destructive">Mermaid Error: ${error instanceof Error ? error.message : 'Unknown error'}</pre>`);
      }
    };

    renderChart();
  }, [chart, resolvedTheme]);

  // Note: dangerouslySetInnerHTML is safe here because:
  // 1. The SVG is generated by mermaid.render() from developer-authored MDX content
  // 2. mermaid has built-in sanitization with securityLevel setting
  // 3. This is not user-generated content from external sources
  return (
    <div
      ref={containerRef}
      className="my-4 flex justify-center overflow-x-auto rounded-lg border bg-background p-4"
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
